version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: devopsPassword
      MYSQL_DATABASE: devopsdb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql


